# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('articleid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='articleid')),
                ('userid', models.CharField(max_length=11)),
                ('classifyid', models.CharField(max_length=11)),
                ('articletitle', models.TextField()),
                ('articlecontent', models.TextField()),
                ('articlestatus', models.CharField(max_length=3)),
                ('coverpicture', models.CharField(max_length=50)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='article_classify',
            fields=[
                ('classifyid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='classifyid')),
                ('classifyname', models.CharField(max_length=11)),
                ('createrClassifyid', models.CharField(max_length=11)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='collection_record',
            fields=[
                ('collectionid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='collectionid')),
                ('collentionUserid', models.CharField(max_length=11)),
                ('collentionarticleid', models.CharField(max_length=11)),
                ('iscollection', models.CharField(max_length=4)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='commentid')),
                ('createrid', models.CharField(max_length=11)),
                ('articleid', models.CharField(max_length=11)),
                ('commentcontent', models.TextField(null=True)),
                ('isdel', models.CharField(max_length=4)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='count',
            fields=[
                ('countid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='countid')),
                ('articleid', models.CharField(max_length=11)),
                ('readUserid', models.CharField(max_length=11)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='leaving_message',
            fields=[
                ('leavingid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='leavingid')),
                ('createrid', models.CharField(max_length=11)),
                ('favoreeid', models.CharField(max_length=11)),
                ('leavingcontent', models.TextField()),
                ('isdel', models.CharField(max_length=4)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('emailid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='emailid')),
                ('email', models.CharField(max_length=50)),
                ('emailcode', models.CharField(max_length=20)),
                ('ecodestatus', models.CharField(max_length=4)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='phone_message',
            fields=[
                ('messageid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='messageid')),
                ('phonenumber', models.CharField(max_length=14)),
                ('messagecode', models.CharField(max_length=20)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
        migrations.CreateModel(
            name='phone_status',
            fields=[
                ('phoneid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='phoneid')),
                ('phonenumber', models.CharField(max_length=14)),
                ('status', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('realname', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=14)),
                ('emailaddress', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(default='auto_now_add')),
                ('useraddress', models.CharField(max_length=100)),
                ('userstatus', models.CharField(max_length=4)),
                ('createdtime', models.DateTimeField(default='auto_now_add')),
                ('updatetime', models.DateTimeField(default='auto_now')),
            ],
        ),
    ]
